### ISSUE TITLE
Refactor Staking Inflation

### ISSUE THREAD

**Issue by schenkty** [vybetoken/vybe#7] opened 2020-10-31 08:06 UTC
Under the current staking system, all calculations are based upon x growth of the supply per month divided by the current holders. This system is complex to understand and is often confusing as stakes are adjusted. Let's move to a flat staking inflation per year divided in real-time.  Staking rates will be determined by the loyalty tier of the stake holder (#8 )

**Comment by schenkty** [comment] 2020-11-11 21:08
@bighandsdev https://github.com/vybetoken/vybe/blob/897ba5ac96f2770cac3a9f8d57ab33292a7332d3/contracts/VybeStake.sol#L168

Let's revise this line to a simple `} else {` so that 5% is default at the start instead of only starting after one month. After reflection, we want stake holders to have a return within their first month.

**Comment by bighandsdev** [comment] 2020-11-12 13:54
@schenkty fixed :)

**Comment by bighandsdev** [comment] 2020-11-12 13:57
ive tested the inflation and it seems to be working as intended now. Other slight tweaks are needed in increase and decrease stake to prevent attacks with the new method. But those aren't related to the inflation itself so i'm going to close this one off.

**Closed by bighandsdev** 2020-11-12 13:57 UTC
